version: "3.7"

services:

  #mynginx: 
    #image: joanflotatsa/votingapp-nginx
    #build: 
      #dockerfile: Dockerfile
      #context: ./nginx
    #ports: 
      #- 8080:80

  mynginx: 
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 8080:80
  
  myredis: 
    image: redis

  myvotingapp: 
    image: joanflotatsa/votingapp
    build: 
      dockerfile: Dockerfile
      context: ./src/votingapp
    environment: 
      REDIS: "myredis:6379"

  mytest: 
    image: joanflotatsa/myvotingapp-test 
    build: 
      context: ./test
    environment: 
      VOTINGAPP_HOST: "myvotingapp"
