apiVersion: v1
kind: Namespace
metadata:
  name: votingapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    events { worker_connections 1024; }

    http {
        include /etc/nginx/mime.types;

        upstream voting{
            server myvotingapp;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://voting/;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }

            location /ws {
                proxy_pass http://voting/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: votingapp
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: nginx
        name: mynginx 
        volumeMounts: 
        - mountPath: /etc/nginx
          name: nginx-conf
      volumes: 
      - name: nginx-conf
        configMap: 
          name: nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf 
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: votingapp
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mynginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myvotingapp
  name: myvotingapp
  namespace: votingapp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: myvotingapp
  template:  
    metadata: 
      labels: 
        app: myvotingapp
    spec:
      containers:
      - image: joanflotatsa/votingapp
        name: votingapp    
        env: 
          - name: REDIS
            value: "myredis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myredis
  name: myredis
  namespace: votingapp
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: myredis
  template:
    metadata:
      labels:
        app: myredis
    spec:
      containers:
      - image: redis
        name: myredis
---
apiVersion: v1
kind: Service
metadata:
  name: myvotingapp
  namespace: votingapp
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: myvotingapp
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: myredis
  namespace: votingapp
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: myredis
  type: ClusterIP